package Server;

public enum DataTypeEnum {
    AUCTION, BUYLOG, CATEGORY, COMPANY, CUSTOMER, DISCOUNTCODE, MANAGER, OFF, OFFREQUEST, PRODUCT, PRODUCTREQUEST, REVIEW, SCORE, SELLLOG, SELLER, SELLERREQUEST,
    SHOPPINGCART, SUPPORTER,OFFATREQUEST, PRODUCTATREQUEST, SELLERATREQUEST, WALLET, BANKACCOUNT;
}
