package Client.GUIControllers;

public enum Page {
    MAKEMANAGERFIRST,MAIN,SIGNIN,SIGNUP,MANAGER,SELLER,CUSTOMER,CREATECOMPANY,SETTINGS,PRODUCTSPAGE,PRODUCTPAGE
    ,MANAGEUSERS,MANAGEREQUESTS,MANAGEPRODUCTS,MANAGEDISCOUNTCODES,MANAGECATEGORIES,EDITFIELDSMANAGER,EDITFIELDSELLER,
    VIEWUSER,CREATEMANAGER,VIEWDISCOUNTCODE,EDITDISCOUNTCODE,CREATEDISCOUNTCODE,VIEWREQUEST
    ,CREATECATEGORY,EDITCATEGORY,SELLEROFFS,SELLERPRODUCTS,SELLERCATEGORIIES,EDITOFF,CREATEOFF
    ,CREATEPRODUCT,VIEWBUYERSPRODUCT,EDITPRODUCT,CUSTOMERDISCOUNTCODES,SHOPPINGCART,PAYMENTPAGE,OFFSPAGE,
    OFFSPRIMEPAGE,BUYLOGSPAGE,BUYLOGSPRIMEPAGE,MONEYPAGE,SELLLOGSPAGE,SELLLOGSPRIMEPAGE,CHATPAGE,AUCTIONPAGE,AUCTIONPAGEPRIME,GROUPCHATPAGE
}
