package GUIControllers;

public enum Page {
    MAKEMANAGERFIRST,MAIN,SIGNIN,SIGNUP,MANAGER,SELLER,CUSTOMER,CREATECOMPANY
    ,MANAGEUSERS,MANAGEREQUESTS,MANAGEPRODUCTS,MANAGEDISCOUNTCODES,MANAGECATEGORIES,EDITFIELDSMANAGER,EDITFIELDSELLER,
    VIEWUSER,CREATEMANAGER,VIEWDISCOUNTCODE,EDITDISCOUNTCODE,CREATEDISCOUNTCODE,VIEWREQUEST
    ,CREATECATEGORY,EDITCATEGORY,SALESHISTORY,SELLEROFFS,SELLERPRODUCTS,SELLERCATEGORIIES,VIEWOFF,EDITOFF,CREATEOFF
}
