package GUIControllers;

public enum Page {
    MAKEMANAGERFIRST,MAIN,SIGNIN,SIGNUP,MANAGER,SELLER,CUSTOMER,CREATECOMPANY
    ,MANAGEUSERS,MANAGEREQUESTS,MANAGEPRODUCTS,MANAGEDISCOUNTCODES,MANAGECATEGORIES,EDITFIELDSMANAGER,
    VIEWUSER,CREATEMANAGER,VIEWDISCOUNTCODE,EDITDISCOUNTCODE,CREATEDISCOUNTCODE,VIEWREQUEST
    ,CREATECATEGORY,EDITCATEGORY


}
