package GUIControllers;

public enum Page {
    MAIN,SIGNIN,SIGNUP,MANAGER,SELLER,CUSTOMER,CREATECOMPANY
    ,MANAGEUSERS,MANAGEREQUESTS,MANAGEPRODUCTS,MANAGEDISCOUNTCODES,MANAGECATEGORIES,EDITFIELDSMANAGER,
    VIEWUSER,CREATEMANAGER

}
